FROM python:latest
WORKDIR /opt/app-root/bin
RUN pip install --upgrade jupyterlab 

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /opt/app-root/src
COPY . .

CMD ["jupyter", "lab", "--port=8888", "--allow-root", "--ip=0.0.0.0"]