# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tq2aaXwqb00inOk-UnCQhLPe3TxNNOKr
"""

def palindrome(number):
  if number < 0:
    return False
  num = str(number)
  if num = num[::-1]:
    return True