FROM python:latest

WORKDIR /opt/app-root/bin

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

WORKDIR /opt/app-root/src
CMD ["jupyter", "lab", "--port=8888", "--allow_origin=*", "--ip=0.0.0.0", "--no-browser"]
