FROM python:3.9-slim
RUN pip install --upgrade pip && \
    pip install notebook
WORKDIR /app
COPY hongyi_dai_hw8.ipynb .
EXPOSE 8888
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

