FROM python:latest
WORKDIR /opt/app-root/bin
RUN pip install --upgrade jupyterlab
COPY assignment-8-riwaz-shrestha.ipynb /app/
CMD ["jupyter", "lab", "--port=8888", "--ServerApp.allow_origin=*", "--ip=0.0.0.0", "--allow-root",  "--no-browser"]
