FROM python:latest

RUN pip install --upgrade pip && pip install --upgrade jupyterlab

WORKDIR /opt/app-root/src

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY assignment8-anissapatel.ipynb .

EXPOSE 8888

CMD ["jupyter", "lab", "--port=8888", "--allow_origin=*", "--ip=0.0.0.0"]
