# student-work/assignment-8/edwin-leck/Containerfile
FROM python:3.10-slim
WORKDIR /app

# Install dependencies
RUN pip install jupyter pandas numpy

# Copy notebook
COPY assignment8-edwinleck.ipynb .

# Configure Jupyter
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--ServerApp.allow_origin='*'"]