FROM python:latest

RUN pip install --upgrade jupyterlab
WORKDIR /opt/app-root/src
COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY assignment8-HrithikShivnauth.ipynb . 

CMD ["jupyter", "lab", "--port=8888", "--ip=0.0.0.0", "--no-browser", "--allow-root"]