# Use a lightweight Python image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
ADD random_number.py /app/random_number.py

# Make the Python script executable
RUN chmod +x /app/random_number.py

# Set the command to execute the Python script
CMD ["python", "./random_number.py"]

