FROM python:3.10

WORKDIR /opt/app-root/src

# Install JupyterLab and packages used in Colab
RUN pip install --upgrade pip \
    && pip install jupyterlab pandas matplotlib numpy seaborn

COPY assignment8-amykouch.ipynb .

EXPOSE 8888

CMD ["jupyter", "lab", "--port=8888", "--allow-root", "--no-browser", "--ip=0.0.0.0"]

