FROM python:latest
RUN pip install --upgrade jupyterlab 
WORKDIR /opt/app-root
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY assignment8-hassandawy.ipynb .


CMD ["jupyter", "lab", "--port=8888", "--ip=0.0.0", "--allow-root"]