# -*- coding: utf-8 -*-
"""palindrome_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtfkCRsblBEwT9ZbrOdjVhIBpaSf37wM
"""

def is_palindrome(x):
    if x < 0 or (x % 10 == 0 and x != 0):  # Negative numbers and numbers ending in 0 (except 0) are not palindromes
        return False

    reversed_half = 0
    while x > reversed_half:
        reversed_half = reversed_half * 10 + x % 10  # Extract last digit and build reversed number
        x //= 10  # Remove last digit from x

    return x == reversed_half or x == reversed_half // 10

test_cases = [
    (121, True),       # Positive palindrome number
    (-121, False),     # Negative number (not a palindrome)
    (531, False),      # Not a palindrome
]

for num, expected in test_cases:
    result = is_palindrome(num)
    print(f"is_palindrome({num}) -> {result} (Expected: {expected})")

