FROM python:3.9-slim

WORKDIR /opt/app-root/bin

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir jupyterlab

WORKDIR /opt/app-root/src

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
